title: NKG Blog
email: contact@nanakkaghar.org
description: >- 
  Stories of Compassion & Change from the Nanak Ka Ghar Foundation.
baseurl: "" 
url: "https://blog.nanakkaghar.org"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap # Add this line